### PR TITLE
Support an empty namespace

### PR DESCRIPTION
**Pull request by bbhoss**

### CODE REVIEW

**Comment by j-mcnally** [comment]
Do we need to handle nil also or is that not a possible value?

**Comment by akira** [comment]
I'd add in a nil in there as well. Looks good besides that.

**Comment by bbhoss** [comment]
I'm not sure what happens if you explicitly add nil, but if you leave the key out it looks like it uses the exq namespace by default

**Comment by akira** [comment]
Merged.

**Comment by akira** [comment]
Thanks!   

Note:  Also updated master to handle nil as well (namespace: nil).

**Comment by j-mcnally** [comment]
Just to document that,

https://github.com/akira/exq/commit/96355b5b1d41643cb02393a0b598bbeb336d5a4e

**Pull request merged**
