### PR TITLE
Feature/swappable serialization

### PR DESCRIPTION
**Pull request by ImJoeWebb**
We understand that this library should be compatible with sidekiq, but for our use case we want to serialize to erlang binary. We have made the json serialization/deserialization configurable in this pull request. Maybe you like it. :)

### CODE REVIEW

**Comment by akira** [comment]
Great!  Will take a look, thanks!

**Comment by akira** [comment]
@ImJoeWebb do you mind squashing your commits?

**Comment by ImJoeWebb** [comment]
@akira there you go!

**Comment by akira** [comment]
@ImJoeWebb ✨ Thanks! ✨

**Pull request merged**
