### PR TITLE
Allow the Redis connection to be setup via a URL

### PR DESCRIPTION
**Pull request by joshk**
The URL takes precedence over the host, password, port and database connection options.

### CODE REVIEW

**Comment by akira** [comment]
:+1: Thanks!

Provides #71

**Comment by joshk** [comment]
Wow, awesome! My first contribution to an Elixir project :)

As a small side question, what is the rough timeline for the next release?

**Comment by akira** [comment]
Awesome!  Releases are usually ad-hoc and depend on what's been added to master.  

If you'd needing to pull from hex.pm, I can bump the hex version and release this tonight/tomorrow.

**Comment by joshk** [comment]
There isn't a super rush, the change isn't urgent as the app I'm building
is still in its early stages.

Thanks for alllllllll the awesome work!

Maybe I'll send some more PRs :)

**Comment by akira** [comment]
Sure!  More PRs would definitely be welcome!  

Also take a look at the [exq_ui](https://github.com/akira/exq) repo as well as there are also some work available there as well.

**Comment by joshk** [comment]
Also thank you for adding the docs on the `url` connection option I added :)

**Comment by akira** [comment]
No problem! :smile:

**Comment by akira** [comment]
@joshk Released this as 0.6.4

**Comment by joshk** [comment]
:heart:

**Pull request merged**
