### PR TITLE
make it possible to use sentinel with latest redix

### PR DESCRIPTION
**Pull request by ananthakumaran**
redix added stricter config validation on 0.11.0. It doesn't allow
host/port config if sentinel option is present.

[1] https://github.com/whatyouhide/redix/commit/4ca9146db158d2918e7399e5881ae1aa349fb79f

### CODE REVIEW

**Comment by sreecodeslayer** [comment]
@ananthakumaran Stumbled upon this PR while i was creating an issue 😄 
Any chance this might get a quick release. Am using sentinel in one of my apps, and currently falling back to github. 

Thanks for the fix!

**Comment by ananthakumaran** [comment]
\cc @akira

**Comment by tschmittni** [comment]
@akira could we get a new version on hex to include this fix?

**Comment by akira** [comment]
Sure let me get it out tonight.

**Comment by akira** [comment]
Just released v0.15.0 🎉

**Pull request merged**
