### PR TITLE
Feature/redis timeout

### PR DESCRIPTION
**Pull request by triptec**
I've been working with this for 3 days now but I'm stuck..

Can't find where I can set the 5000 in this call:

07:06:13.038 [error] GenServer :perf terminating
Last message: :timeout
State: %Exq.Manager.Server.State{enqueuer: :perf_enqueuer, host: "58b44ef1c813", namespace: "test", pid: #PID<0.1549.0>, poll_timeout: 50, queues: ["default"], redis: #PID<0.1550.0>, scheduler: :perf_scheduler, scheduler_poll_timeout: 200, stats: #PID<0.1551.0>, work_tabl
e: 7389325}
** (exit) an exception was raised:
    ** (ErlangError) erlang error: {:timeout, {:gen_server, :call, [#PID<0.1550.0>, {:request, [["*", '2', "\r\n"], [["$", '4', "\r\n", "LPOP", "\r\n"], ["$", '18', "\r\n", "test:queue:default", "\r\n"]]]}, 5000]}}
        (stdlib) gen_server.erl:212: :gen_server.call/3
        lib/exq/redis/connection.ex:105: Exq.Redis.Connection.lpop!/2
        lib/exq/redis/job_queue.ex:70: Exq.Redis.JobQueue.dequeue/3
        lib/exq/redis/job_queue.ex:118: Exq.Redis.JobQueue.dequeue_random/3
        lib/exq/manager/server.ex:159: Exq.Manager.Server.dequeue_and_dispatch/2
        lib/exq/manager/server.ex:138: Exq.Manager.Server.handle_info/2
        (stdlib) gen_server.erl:615: :gen_server.try_dispatch/4
        (stdlib) gen_server.erl:681: :gen_server.handle_msg/5

Any pointers are welcome

### CODE REVIEW

**Comment by akira** [comment]
Thanks for changes and adding those tests, great help.  This is a tricky one, will see if I can find something :smile:

**Comment by akira** [comment]
I made a pull request to your branch with some changes, let me know if you had thoughts.  I added a try / catch to handle the timeout in the GenServer, and a few tweaks to the test. 

Another question - for the delay, is it usually the same instruction on the Redis end, or does it occur in different places? Just curious if something inefficient is being sent, or if it's just a delay with every instruction, etc...

**Comment by triptec** [comment]
Thanks for your help, greatly valued! I updated the tests and added one that shows that it doesn't work without the genserver_timeout.

About the delay I have no clue, I'm going to put this in semi production and see what might be the next hurdle.

**Comment by triptec** [comment]
is there anything else I would need to do to get this merged?

**Comment by akira** [comment]
:+1: Thanks!

**Pull request merged**
