### PR TITLE
Support load from runtime env for more config params

### PR DESCRIPTION
**Pull request by LysanderGG**
First of all, thank you for the great library.

When using it I was surprised that some of the config parameters could use the syntax  `{:system, VAR}` and some others could not.

This MR adds `{:system, VAR}` format support for integer parameters that are not supporting it yet and to boolean parameters.

In addition to integers, I supported `:infinity` for the `:concurrency` parameter. I assumed that no other parameter could be `:infinity` as there are no such tests or documentation.

I can add support for list of string in this or another MR (for `:queues`) if wanted.
A proposition of format could be splitting on comas, i.e. `"a,b,c"` parsed as `["a", "b", "c"]`.

Any suggestion is welcome.

### CODE REVIEW

**Comment by akira** [comment]
Sure, thanks for PR!  👍   Commas could work for array params if needed.

**Comment by akira** [comment]
@LysanderGG Actually it looks like the build failed?

**Comment by LysanderGG** [comment]
@akira I fixed it

**Comment by akira** [comment]
👍 Thanks!

**Pull request merged**
