### PR TITLE
Remove self() warning

### PR DESCRIPTION
**Pull request by lpil**

### CODE REVIEW

**Comment by akira** [comment]
@lpil I am getting an error with this:

```
akira@Alexs-MacBook-Pro ~/development/erlang/exq (master) $ MIX_ENV=test mix test --no-start --warnings-as-errors
** (Mix) Could not invoke task "test": 1 error found!
--warnings-as-errors : Unknown option
```

**Comment by lpil** [comment]
oops, my bad!

**Comment by lpil** [comment]
Something funky seems to have happened in one of the Elixir versions. Not sure what caused that

**Comment by akira** [comment]
👍

**Pull request merged**
