### PR TITLE
Bump version of Poison

### PR DESCRIPTION
**Pull request by frahugo**
Allow Poison 5.0.0 to be used.

### CODE REVIEW

**Comment by ananthakumaran** [comment]
@frahugo do you know if I can find the changelog somewhere? I am happy to merge it, just wondering if there are any breaking changes that we need to know about.

**Comment by frahugo** [comment]
> @frahugo do you know if I can find the changelog somewhere? I am happy to merge it, just wondering if there are any breaking changes that we need to know about.

@ananthakumaran The CHANGELOG is at the root. I ran the test locally with `Poison` as the Json library and tests were green. I guess it would not break anything as the json is used to serialize and deserialize data for the jobs. Maybe someone else who uses Poison can jump in?

**Comment by ananthakumaran** [comment]
I was asking about poison changelog. Seems like they don't maintain any.

**Comment by ananthakumaran** [comment]
@frahugo released

**Pull request merged**
