### PR TITLE
Changes:

### PR DESCRIPTION
**Pull request by sineed**
1. Use `Connection#qp` in `JobStats#realtime_stats`;
2. Add test for `realtime_stats`.

### CODE REVIEW

**Comment by sineed** [comment]
Related to #100 
@akira I'm new to Elixir so there might be code smells.

I'm not quite confident in implemented test. I assert only size of generated stats, not the time of job processing. I tried to find a dep like Ruby `Timecop` gem but had no luck.
Also there might be a floating test error: enqueue of two jobs which are not split by the `:timer.sleep` may be done in different seconds. 

Please take a look.

**Comment by akira** [comment]
The changes look good. 

As far as the test, we're trying to avoid :timer.sleep for tests if possible.  I think this would be better as a lower level `job_stat_test`.  You can add failures and successes through `JobStat.record_failure` and JobStat.record_processed` and then just issue the realtime API without having to wait.

**Comment by sineed** [comment]
I've made changes following your advice. Need squash?

**Comment by akira** [comment]
:+1: looks good, thanks!

**Pull request merged**
